### ISSUE TITLE
help: how to correctly setup your neovim .config?

### ISSUE THREAD

**Issue by m1guer** [mcauley-penney/nvim#1]

**Comment by mcauley-penney** [comment]
How far did you get and What sort of problems are you running into? As of right now, it requires at least fzf to be installed manually.

**Comment by m1guer** [comment]
these 3:
![image](https://github.com/mcauley-penney/nvim/assets/91486755/c5217d91-b5b7-4289-aea4-e4f2bf6d45ce)
![image](https://github.com/mcauley-penney/nvim/assets/91486755/4b2f69ad-d5dc-40d8-af66-466ba18fa157)
![image](https://github.com/mcauley-penney/nvim/assets/91486755/c5eea3f2-9d7c-4388-bb30-b8caceed5db1)

**Comment by mcauley-penney** [comment]
It seems like the second error (not being able to find the color scheme) is causing the third error (gitsigns cfg not being able to get a color, because the hex_to_rgb function is returning a nil). This is probably caused by the error you're getting with yanky. It seems that that error is stopping lazy from loading all the plugins. 

So, I'd probably comment out yanky for now, try and get the rest of it to load, then try yanky again after.

**Comment by mcauley-penney** [comment]
Also, I've never seen that error with yanky. If you're using something other than Linux, I have zero idea how that works. It seems like it's an issue with clipboards. I'd personally read yanky's issues, docs, then source code to figure it out, in that order

**Comment by m1guer** [comment]
im using arch linux, i will search more thx 

> Also, I've never seen that error with yanky. If you're using something other than Linux, I have zero idea how that works. It seems like it's an issue with clipboards. I'd personally read yanky's issues, docs, then source code to figure it out, in that order

**Comment by mcauley-penney** [comment]
Okay, I think I figured it out. So, I searched yanky's issues, docs, then read their source code. Based on the source code, my best guess was that you don't have a package installed in arch to provide a system clipboard. Then I realized I define my clipboard explicitly in my init.lua file. The issue is *probably* that you don't have xsel installed. 

Going to `init.lua` and removing the code that starts with `vim.g.clipboard` is a good place to start
